using Microsoft.CodeAnalysis;
using System.Text;
using Ufw.Roslyn.SourceGen.Controllers.Processors.BindingClasses;
using Ufw.Roslyn.SourceGen.Controllers.Processors.Endpoints;

namespace Ufw.Roslyn.SourceGen.Controllers.Emitters;

internal sealed class MappingClassEmitter(SourceProductionContext context)
{
    private const string API_ENDPOINT_MAPPING_FULL_NAME = "global::Ufw.Roslyn.Controllers.Mapping.ApiEndpointMapping";
    private const string ACTIVATOR_FULL_NAME = "global::Ufw.Roslyn.Controllers.Internals.Activator";

    public void Emit(BindingClassProcessorResult result)
    {
        try
        {
            string source = GeneratePartialClassSource(result);
            context.AddSource($"{result.MappingClass.ClassSymbol.Name}.EndpointBindings.g.cs", source);
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "UFWAPI001",
                    "Error generating API endpoint mappings",
                    "Error generating API endpoint mappings for {0}: {1}",
                    "UfwApiGenerator",
                    DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                Location.None,
                result.MappingClass.ClassSymbol.Name,
                ex.Message));
        }
    }

    private static string GeneratePartialClassSource(BindingClassProcessorResult result)
    {
        StringBuilder sb = new();
        // Start generating the source
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(result.NamespaceName))
        {
            sb.AppendLine($"namespace {result.NamespaceName};");
            sb.AppendLine();
        }

        // Generate the partial class with mappings array
        sb.AppendLine(
            $$"""
            partial class {{result.ClassName}}
            {
                [global::{{result.CompilerGeneratedFullName}}]
                private static readonly {{API_ENDPOINT_MAPPING_FULL_NAME}}<{{result.RequestEnvelopeFullName}}, {{result.ResponseEnvelopeFullName}}>[] {{result.MappingsFieldName}} =
                [
            """);

        // Generate mapping entries
        foreach (EndpointProcessorResult endpoint in result.Endpoints)
        {
            sb.AppendLine(
                $$"""
                        {{result.FactoryFullName}}.Map{{endpoint.GenericParams}}("{{endpoint.HttpMethod}}", "{{endpoint.Route}}", priority: {{endpoint.Priority}}, static async (serviceProvider, initializeAsync{{endpoint.RequestParam}}, cancellationToken) =>
                        {
                            {{endpoint.ControllerTypeFullName}} controller = await {{ACTIVATOR_FULL_NAME}}.CreateControllerAsync<{{endpoint.ControllerTypeFullName}}>(serviceProvider, initializeAsync, cancellationToken);
                            return await controller.{{endpoint.MethodName}}({{endpoint.MethodArgs}}cancellationToken);
                        }),
                """);
        }

        sb.AppendLine($$"""
                ];

                [global::{{result.CompilerGeneratedFullName}}]
                protected override {{API_ENDPOINT_MAPPING_FULL_NAME}}<{{result.RequestEnvelopeFullName}}, {{result.ResponseEnvelopeFullName}}>[] {{result.GetMappingsMethodName}}() => {{result.MappingsFieldName}};
            }
            """);

        return sb.ToString();
    }
}
