using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using Ufw.Pipes.Shared.Model;
using Ufw.Pipes.Shared.Serialization;
using Ufw.Roslyn.Controllers.Mapping;
using Ufw.Roslyn.Controllers.Mapping.Attributes;
using Ufw.Roslyn.Controllers.Mapping.Delegates;
using Ufw.Systemd.Api.Controllers;
using Ufw.Systemd.Api.Endpoints;
using Ufw.Systemd.Api.Framework;
using Ufw.Roslyn.Controllers.Internals;
using Ufw.Pipes.Shared.Model.Responses.Domain;
using Ufw.Pipes.Shared.Model.Requests.Domain;

namespace Ufw.Systemd.Api;

[ApiControllerRegistration<RulesController>]
[ApiControllerMappingGenerator<UfwApiEndpointMappingFactory, IMessage, IMessage>]
internal sealed partial class UfwApiEndpointMap : ApiEndpointMap<IMessage, IMessage>
{
    private static readonly NotFoundEndpoint s_notFound = new();
    private static readonly UnsupportedMethodEndpoint s_unsupportedMethod = new();

    protected override FrozenSet<string> SupportedMethods { get; } = RequestMethod.GetNames().ToFrozenSet();

    public override IApiEndpoint<IMessage, IMessage> GetNotFoundEndpoint() => s_notFound;

    public override IApiEndpoint<IMessage, IMessage> GetUnsupportedMethodEndpoint() => s_unsupportedMethod;

    // TODO: this should be generated by Ufw.Roslyn.SourceGen.ApiEndpointBindingGenerator.
    // - any classes decorated with [ApiControllerMappingGenerator] should be considered for generation.
    // - T1 of ApiControllerMappingGenerator<TFactory, TRequestEnvelope, TResponseEnvelope> is the factory type implementing IApiEndpointMappingFactory<TRequestEnvelope, TResponseEnvelope>
    // - all controllers registered on the generator class via [ApiControllerRegistration<TController>] must be processed.
    // - controllers may have a [Ufw.Roslyn.Controllers.Routing.Route] attribute to specify a base route for all endpoints in the controller.
    //   This attribute may contain an optional Priority property that should be considered when generating the endpoint mappings.
    // - all public methods on the controller decorated with [Get|Post|Put|Delete] attributes (with sub route specifications / priorities) must be mapped to an endpoint mapping.
    // - bound methods must match these conditions:
    //   - ValueTask<TResponse> returning
    //   - (optional) request parameter of type TRequest
    //   - CancellationToken parameter
    // - depending on the presence of a request parameter, the corresponding TMappingFactory.Map overload must be used.
    // - a full route must be constructed by combining the (optional) controller base route and the (optional) method sub route, although one of them must be present.
    // - the lowest priority value wins when both controller and method specify priorities, if neither specify priorities, default to 0.
    private static readonly ApiEndpointMapping<IMessage, IMessage>[] s_mappings =
    [
        UfwApiEndpointMappingFactory.Map<RuleListResponse>(method: "GET", route: "/api/v1/rules/list", priority: 0, static async (serviceProvider, initializeAsync, cancellationToken) =>
        {
            RulesController controller = await Roslyn.Controllers.Internals.Activator.CreateControllerAsync<RulesController>(serviceProvider, initializeAsync, cancellationToken);
            return await controller.GetRulesAsync(cancellationToken);
        }),
        UfwApiEndpointMappingFactory.Map<DeleteRuleRequest, IResponseMessage>(method: "DELETE", route: "/api/v1/rules", priority: 0, static async (serviceProvider, initializeAsync, request, cancellationToken) =>
        {
            RulesController controller = await Roslyn.Controllers.Internals.Activator.CreateControllerAsync<RulesController>(serviceProvider, initializeAsync, cancellationToken);
            return await controller.DeleteRuleAsync(request, cancellationToken);
        }),
        // general structure for future mappings:
        // TFactory.Map<TResponse[, TRequest]>(method: "<HTTP method from method attribute>", route: "[CONTROLLER_ROUTE]/[SUB_ROUTE]", priority: <Min(CONTROLLER_PRIORITY, SUB_PRIORITY)>, static async (serviceProvider, initializeAsync[, request], cancellationToken) =>
        // {
        //     [ControllerType] controller = await Roslyn.Controllers.Internals.Activator.CreateControllerAsync<[ControllerType]>(serviceProvider, initializeAsync, cancellationToken);
        //     return await controller.[MethodName]([request, ]cancellationToken);
        // }),
    ];

    protected override ApiEndpointMapping<IMessage, IMessage>[] GetMappings() => s_mappings;
}