<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ufw.Ipc.Shared\Ufw.Ipc.Shared.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(OS)' == 'Windows_NT'">
		<Compile Remove="**\*.Unix.cs"></Compile>
		<None Include="**\*.Unix.cs"></None>
	</ItemGroup>
	
	<ItemGroup Condition="'$(OS)' != 'Windows_NT'">
		<Compile Remove="**\*.Win32.cs"></Compile>
		<None Include="**\*.Win32.cs"></None>
	</ItemGroup>
</Project>
